TRUNCATE TABLE AD;
TRUNCATE TABLE ADR;
TRUNCATE TABLE CA;
TRUNCATE TABLE CR;
TRUNCATE TABLE CV;
TRUNCATE TABLE IMP_AD;
TRUNCATE TABLE IMP_ADR;
TRUNCATE TABLE IMP_CA;
TRUNCATE TABLE IMP_CR;
TRUNCATE TABLE IMP_CV;

COMMIT;
EXIT;